### ISSUE TITLE
API支持.rst中描述了engine_method,可否支持robinhood/faust,实现分布式+异步

### ISSUE THREAD

**Issue by zfsamzfsam** [ctpbee/ctpbee#10]
**robinhood/faust**
	https://github.com/robinhood/faust
	
       Faust is a **stream processing library**, porting the ideas from Kafka Streams to Python.

	It is used at Robinhood to 
		**build high performance distributed systems and 
		real-time data pipelines that process billions of events every day.**

	Faust provides both **stream processing and event processing**, 
		sharing similarity with tools such as Kafka Streams, Apache Spark/Storm/Samza/Flink.

	It does not use a DSL, it's just Python! 
		**This means you can use all your favorite Python libraries when stream processing: NumPy, PyTorch, Pandas, NLTK, Django, Flask, SQLAlchemy,...**
	
		Faust requires Python 3.6 or later for the new async/await syntax, and variable type annotations.

**Comment by somewheve** [comment]
分布式我们是准备自己再写一套方案. 让用户可以快速部署代码. 这个我看看
