### ISSUE TITLE
dev分支中有支持puppet,也应该可以支持JaysonAlbert/tdx_api

### ISSUE THREAD

**Issue by zfsamzfsam** [ctpbee/ctpbee#11]
JaysonAlbert/tdx_api
         https://github.com/JaysonAlbert/tdx_api

**Comment by somewheve** [comment]
哇 没注意这个issue 不好意思 , 是计划支持的 ..  后面会支持tdx的  
最近在写回测模块  

感谢关心

**Comment by somewheve** [comment]
如果想进一步探讨 ,欢迎邮件联系   somewheve@gmail.com
