### ISSUE TITLE
股票功能需求

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#120]
**需求/request**

需要实现了股票的回测功能, 日线级别的回测以及股票T0级别的回测，注意需要和现有接口进行兼容 

**最终表现效果 / result
多品种级别的股票能够进行回测， 同时收益与沪深300收益进行对比

**Comment by vinsvison** [comment]
看看是否可以结合qlib

**Comment by qtbgo** [comment]
现在可以通过vnpy的xtp接口进行股票实盘仿真了吗？
