### ISSUE TITLE
一个征集需求

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#125]
**需求/request**

准备重写所有的函数注解 生成和tq一样的文档， 但是我一个人可能精力不足， 需要有人帮我review 代码 。也就是我提交的注解 以防出现错字 ····

**最终表现效果 / result**
获取完整的ctpbee文档

**Comment by somewheve** [comment]
如果有兴趣 可以给我发邮件 或者回复issue

**Comment by quantcn** [comment]
请问，可以把backtrader接上ctpbee的api，进而接通ctp进行实盘交易吗？backtrader是一个开源量化框架https://github.com/mementum/backtrader

**Comment by somewheve** [comment]
emmmm  应该是可以的 不过没那么自动化
