### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by 1wy** [ctpbee/ctpbee#127]
请问如何运行回测？
我尝试了looper_example.py，但没有data_api 模块
又尝试了[文档](https://docs.ctpbee.com/)里的方式，但没有Vessel模块

如果可以的话，最好给一个样例数据，
直接读取该文件能够跑通。

**Comment by somewheve** [comment]
我稍後給完整的demo 我們內部是已經在用這個回測系統了  但是我沒怎麼寫文檔

**Comment by somewheve** [comment]
不好意思哈
