### ISSUE TITLE
self.app.center.get_tick()报错

### ISSUE THREAD

**Issue by liubola** [ctpbee/ctpbee#131]
**Describe the bug / 问题描述**
> self.app.center.get_tick()报错
TypeError: 'TickData' object is not subscriptable

查看源代码后发现调用下面这个代码
self.app.recorder.get_tick()[:-1]

但是self.app.recorder.get_tick()貌似只返回单个TickData

**Comment by somewheve** [comment]
对的 看下源码  这个接口我不怎么用， 可能写的有问题 。 一般行情是自己在on_tick上面收就好了
