### ISSUE TITLE
策略构造函数中无法使用logger

### ISSUE THREAD

**Issue by yinhuanhuan** [ctpbee/ctpbee#136]
在策略的构造函数中使用self.info方法会报错AttributeError: 'NoneType' object has no attribute 'logger'

在on_tick里可正常使用self.info方法。

**Comment by somewheve** [comment]
肯定无法在建造者方法里面用啊 此时都还没初始化

**Comment by somewheve** [comment]
推荐在on_init 中使用info方法 这个是仓位就绪后就会被调用

**Comment by yinhuanhuan** [comment]
T.T 好的，谢谢，哈哈。以为在父类里初始化了。
