### ISSUE TITLE
回测遇到问题，附图。请帮忙解决一下

### ISSUE THREAD

**Issue by myougg** [ctpbee/ctpbee#161]
![ctp问题](https://user-images.githubusercontent.com/55285471/144403389-f21e2a11-f07a-4c15-8d4a-3479db6002eb.png)

**Comment by somewheve** [comment]
记录的挂单平仓量可能不对 需要检查下你的平仓指令

**Comment by myougg** [comment]
嗯嗯，找到原因了，谢谢
