### ISSUE TITLE
关于TradingDay

### ISSUE THREAD

**Issue by Ken-LiuL** [ctpbee/ctpbee#164]
你好，我看到helper.py里面的TradingDay部分被注释掉了，请问下交易时间和节假日这一块 框架这里是怎么处理的呢

**Comment by somewheve** [comment]
看https://github.com/ctpbee/ctpbee/blob/c504e141c0a6fb2c5509bb6a77494c592997c0d4/ctpbee/date.py#L1   里面有详细的交易日历 每年更新一次
