### ISSUE TITLE
交易所套利指令的平仓支持

### ISSUE THREAD

**Issue by zzeric** [ctpbee/ctpbee#175]
开仓是能支持的，但是开仓后，交易所是分拆成一对持仓，平仓时CTPBEE是按套利代码查持仓的，所以会发现仓位不足，平仓失败。所以对IPS / SP这类代码的平仓，可以不检测。

**Comment by zzeric** [comment]
或者检查合约对的持仓量

**Comment by somewheve** [comment]
套利持仓我还没做过检测 你可以提个pr麻

**Comment by zzeric** [comment]
我试试哈

**Comment by somewheve** [comment]
注意别影响以前的代码哈  向前兼容

**Comment by hxhrtrading** [comment]
请问有交流群么？

**Comment by somewheve** [comment]
有个实盘群  一般来说是解答实盘中产生的问题的   不涉及交流

**Comment by somewheve** [comment]
https://github.com/ctpbee/ctpbee/pull/259 此处开始增加对套利指令的支持 

下一步下单和仓位需要进一步测试

**Comment by somewheve** [comment]
功能上我了解了 感觉写起来有点麻瓜  我在想要不要增加一个套利操作的函数 带上额外的仓位检查
