### ISSUE TITLE
请问on_bar里bar的datetime字段是bar结束的时间还是开始的时间？

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#178]
如题，谢谢

**Comment by somewheve** [comment]
开始的时间  对照下文华或者快期就好了

qtbgo ***@***.***> 于2022年4月13日周三 13:56写道：

**Comment by qtbgo** [comment]
可以设置成bar结束时间吗？

**Comment by somewheve** [comment]
自己设置修改 + 个timedelta 就好了

qtbgo ***@***.***> 于2022年4月15日周五 14:57写道：

**Comment by qtbgo** [comment]
再请教，ctp tick的快照时间，是tick的开始时间还是结束时间？猜测也是开始时间，是吗？

**Comment by somewheve** [comment]
ctp的tick是某个时间下切出来的 orderbook， 这里和ctpbee不一样， 他这个是产生的时间 也就是结束时间

**Comment by qtbgo** [comment]
非常感谢！ 再请教一下，ctpbee里的1分钟k线，比如 时间为10:00:00的1分钟k线，包含的tick时间范围是(10:00:00.000, 10:01:00.000]，还是[10:00:00.000, 10:01:00.000) ?也就是 时间范围左开右闭，还是左闭右开？

**Comment by somewheve** [comment]
https://github.com/ctpbee/ctpbee/blob/56371db8d05570e7f9b4bd38b7094fd3850263f8/ctpbee/data_handle/generator.py#L71  自己看下代码吧

**Comment by qtbgo** [comment]
看得有点头晕，似乎1分钟线的时间不是总是处于整分钟处。有可能会出现比如14:10:33.500这样的1分钟线的时间，是吧？与我们一般感觉必须处于整分钟时间不太一致

**Comment by somewheve** [comment]
技术多学学吧 不然你这做量化也没条件  很多策略都很复杂的  技术要过关
