### ISSUE TITLE
ctpbee中，盘中怎么捕获断线事件和重新连接成功事件

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#184]
盘中发生断线，以及之后自动重新连上，这两个事件ctpbee里有没有回调函数对应？我需要在这里面做些处理。
谢谢！

**Comment by qtbgo** [comment]
是不是要在signals.py里扩展onFrontConnected，onFrontDisconnected信号？

**Comment by somewheve** [comment]
是的

qtbgo ***@***.***> 于2022年4月24日周日 18:12写道：

**Comment by qtbgo** [comment]
楼主，这个功能很重要啊，生产环境实盘时，若断线，则自动重连后，第一根k线的合成需要特殊处理。所以需要在这里做工作。楼主能否加上？或者给点提示，该怎么要改哪几个地方？

**Comment by somewheve** [comment]
你都少数据了k线啥的还重要吗   。。。。  你都拿不到那个数据 就是一个脏的k线

**Comment by somewheve** [comment]
难道能不能正确的k线补回来吗 你少了20s的tick 你再怎么补都是错的

**Comment by somewheve** [comment]
建议你先多研究策略 少研究系统 能跑就行 后面再来纠结 如果你策略写好了 放云服务器上面 基本问题不大

**Comment by qtbgo** [comment]
谢谢楼主的建议，不过断线时，我还要干一些其它事情。所以还是想捕获它。
我在BeeTdApi里，看到onFrontDisconnected断线事件会调用
	  self.on_event(type=EVENT_LOG, data=f"交易连接断开，原因{reason}")
	  所以我猜测EVENT_LOG可代表断线事件。
	  
于是我做了如下修改：
	在level.py的CtpbeeApi里
	1 map和参数增加 EVENT_LOG 相关
	       map = {
            EVENT_TIMER: cls.on_realtime,
            EVENT_TICK: cls.on_tick,
            EVENT_BAR: cls.on_bar,
            EVENT_ORDER: cls.on_order,
            EVENT_TRADE: cls.on_trade,
            EVENT_POSITION: cls.on_position,
            EVENT_ACCOUNT: cls.on_account,
            EVENT_CONTRACT: cls.on_contract,

            EVENT_LOG: cls.on_log, # 这是新加的
        }
        parmeter = {
            EVENT_TIMER: EVENT_TIMER,
            EVENT_POSITION: EVENT_POSITION,
            EVENT_TRADE: EVENT_TRADE,
            EVENT_BAR: EVENT_BAR,
            EVENT_TICK: EVENT_TICK,
            EVENT_ORDER: EVENT_ORDER,
            EVENT_SHARED: EVENT_SHARED,
            EVENT_ACCOUNT: EVENT_ACCOUNT,
            EVENT_CONTRACT: EVENT_CONTRACT,

            EVENT_LOG: EVENT_LOG, # 这是新加的
        }
	2 增加 on_log 方法
	   def on_log(self, msg):
        '''处理连线、断线、登录等事件'''
        pass
	
  遗憾的是，on_log还是无法激发，不知我改的哪里不对啊？

**Comment by somewheve** [comment]
https://github.com/ctpbee/ctpbee/blob/56371db8d05570e7f9b4bd38b7094fd3850263f8/ctpbee/record.py#L89  

你在这个函数里面加一个@helper_call 试试  

参见https://github.com/ctpbee/ctpbee/blob/56371db8d05570e7f9b4bd38b7094fd3850263f8/ctpbee/record.py#L94

**Comment by qtbgo** [comment]
成功了，谢谢啦
