### ISSUE TITLE
def run_forever(app)已经可以用了吗？

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#187]
楼主，def run_forever(app)这个永久运行app的是不是可以用？
我看其中主要方法是app.reload()，相对于app自己的app.start(),好像缺少了启动running_timer线程，不知怎么回事？
另外 hickey似乎也是处理永久运行的。
不知楼主推荐的永久运行是应该用哪个？

**Comment by somewheve** [comment]
hickey 自动处理的

**Comment by qtbgo** [comment]
以下是我写得一段样本代码
       self.app = CtpBee("app", __name__, refresh=True) 
        self.main_ctpbee_api = MyCtpbeeApi("main_ctpbee_api", md_queue=self.q_feed_qlive, timeframe=self.p.timeframe)
        self.app.config.from_mapping(ctp_setting)
        self.app.add_extension(self.main_ctpbee_api)       
           
        hickey.start_all(self.app)
但报如下错误。 hickey.start_all( )的参数在这个case里应该写什么呢？谢谢啦
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\func.py", line 329, in start_all
    raise TypeError(f"请检查你传入的app_func是否是创建app的函数,  而不是{type(app_func)}")
TypeError: 请检查你传入的app_func是否是创建app的函数,  而不是<class 'ctpbee.app.CtpBee'>

**Comment by somewheve** [comment]
def create_app():
    app = CtpBee("app", name, refresh=True)
    return app

hickey.start_all(create_app)

**Comment by qtbgo** [comment]
找到一篇，是参考这个弄吧 https://blog.csdn.net/weixin_39879219/article/details/111333934

**Comment by qtbgo** [comment]
> ```
> def create_app():
>     app = CtpBee("app", name, refresh=True)
>     return app
> 
> hickey.start_all(create_app)
> ```

非常感谢。

**Comment by somewheve** [comment]
他会开一个子进程来跑这个ctpbee  大概是这个意思

**Comment by qtbgo** [comment]
仔细看了，这个要杀进程，可是我是把ctpbee合并到我自己的程序中，我程序中有个大循环需要一直引用ctpbeeapi，所以以上方法可能不行。想请教，就像如下使用，能不能7*24正常运行？如果不行，能不能在ctpbeeapi对象的on_realtime里根据本机时间切换frozen标志？
self.app = CtpBee("app", name, refresh=True)
self.main_ctpbee_api = MyCtpbeeApi("main_ctpbee_api", md_queue=self.q_feed_qlive, timeframe=self.p.timeframe)
self.app.config.from_mapping(ctp_setting)
self.app.add_extension(self.main_ctpbee_api)
self.app.start()
