### ISSUE TITLE
process_tick_event里需要验证tick是不是脏数据吗？

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#189]
如题，不验证的话，会不会对position_manager引入脏数据？
`    @helper_call
    def process_tick_event(self, event: Event):
        tick: TickData = event.data
        # 这里是否需要利用合约状态对tick进行校验。
        # 或者利用时间来校验脏数据，否则position_manager会不会出问题
        self.ticks[tick.local_symbol] = tick
        self.position_manager.update_tick(tick, tick.pre_settlement_price)
        # 生成datetime对象
        if not tick.datetime:
            if '.' in tick.time:
                tick.datetime = datetime.strptime(' '.join([tick.date, tick.time]), '%Y%m%d %H:%M:%S.%f')
            else:
                tick.datetime = datetime.strptime(' '.join([tick.date, tick.time]), '%Y%m%d %H:%M:%S')
        bm = self.generators.get(tick.local_symbol, None)
        if bm:
            bm.update_tick(tick)
        if not bm:
            self.generators[tick.local_symbol] = generator(self.app)
            self.generators[tick.local_symbol].update_tick(tick)`

**Comment by somewheve** [comment]
这个问题我还没想过 这个确实是一个问题  
等我这阵子策略写完了 就来处理这个 最近太忙了  到时候ctpbee要做一个大的优化
