### ISSUE TITLE
穿透测试错误

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#190]
大佬，我在测试穿透验证。
配置文件里已经设置接口为 ctp_se
然后运行测试程序，报错如下：
ValueError("错误参数")

追踪到源码，发现
E:\myquant\venv_quant389\Lib\site-packages\ctpbee\interface_init_.py文件里：

class Interface:
""" 按照接口进行加载而不是一次性进行加载 """

@classmethod
def load_interface(cls, interface):
    if interface == "ctp":
        from ctpbee.interface.ctp import BeeTdApi, BeeMdApi
        return BeeMdApi, BeeTdApi
    if interface == "looper":
        from ctpbee.interface.looper import LooperMe, LooperYou
        return LooperMe, LooperYou
    if interface == "ctp_mini":
        from ctpbee.interface.ctp_mini import MMdApi, MTdApi
        return MMdApi, MTdApi
    else:
        raise ValueError("错误参数")
并没有ctp_se接口。所以报错误参数错误。 怎么解决呢？急啊！

**Comment by somewheve** [comment]
这个是很早期的了 我删除了需要你自己去下载6.6.1的版本的ctp仿真穿透的dll

**Comment by somewheve** [comment]
在那个ctpbee_api的目录下面 替换就好了哈

**Comment by somewheve** [comment]
用完再换回来

**Comment by qtbgo** [comment]
嗯，我替换了。主要问题是配置文件里不能写 ctp_se，还是应该写ctp，这样就可以了

**Comment by qtbgo** [comment]
还是有一些问题，可能是版本问题。现在期货公司给的是看穿式监管评测版本(版本号:v6.6.5_CP_20210831 10:47:51.576)。请问要怎么做才能测试成功?是把所有同名文件替换ctpbee_api中的就可以了吗？

**Comment by qtbgo** [comment]
是不是应该按如下步骤做：
（1）将6.6.5版本中的h头文件替换ctpbee_api中include/ctp/ 四个头文件
（2）用6.6.5版的 thostmduserapi_se.dll 和 thostmduserapi_se.lib， thosttraderapi_se.dll 和 thosttraderapi_se.lib 替换cetbee_api中ctp目录下的同名文件（for windows）； linux则替换.so 文件
（3） 然后 python setup.py build 进行编译 没啥问题 就 python setup.py install.

**Comment by somewheve** [comment]
替换dll和so文件就可以 你可以尝试下

**Comment by qtbgo** [comment]
我是windows下，6.6.5单纯替换两个dll不行，会自动退出。现在还是用6.6.1版才行。
