### ISSUE TITLE
RuntimeError:can not open CFlow file in line 338 of file ..\..\source\userapi_se\ThostFtdcUserApiImplBase.cpp

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#191]
运行app.start()的时候报错

**Comment by aooife9** [comment]
我电脑用户名是英文也还是报这个错
RuntimeError:can not open CFlow file in line 338 of file ../../source/userapi_se/ThostFtdcUserApiImplBase.cpp

**Comment by bob-lytton** [comment]
> 我电脑用户名是英文也还是报这个错 RuntimeError:can not open CFlow file in line 338 of file ../../source/userapi_se/ThostFtdcUserApiImplBase.cpp

我也遇到过，我是在pycharm里运行的时候报的错，最后发现时working directory下无法创建.con文件导致的

**Comment by somewheve** [comment]
这个问题的解决文案是当前程序无法在当前工作目录创建.con文件的 权限问题嘛 ？

**Comment by bob-lytton** [comment]
我的case里，无法创建.con文件应该是因为找不到目录，因为我把pycharm运行配置里的working directory改对了后就正常了，这期间应该没有发生权限变化

**Comment by somewheve** [comment]
okok
