### ISSUE TITLE
穿透式测试接收合约出错，无法下单

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#195]
我更换了穿透式api后进行穿透式测试发现会出现报单错误，找不到合约，而同一套代码在simnow是没问题的。
![image](https://user-images.githubusercontent.com/43166853/177233687-5be4ccae-e904-46da-8575-66d3d52f1862.png)

看这个local_symbol这一列，展示的是合约是不对的

**Comment by somewheve** [comment]
那要问你的客户经理 能下啥合约啊

**Comment by somewheve** [comment]
这个是你自己开发的界面 ？

**Comment by LJingnan** [comment]
@somewheve 谢谢大佬，我发现我应该用6.6.1的api，期货公司开始让我用6.3.9把我搞懵了

**Comment by somewheve** [comment]
搞定就行
