### ISSUE TITLE
开盘时tick接受延时严重

### ISSUE THREAD

**Issue by Wilson-G** [ctpbee/ctpbee#199]
hi，首先感谢开发出这么好用的工具，代码和文档都很赞！

就是最近开盘时发现tick好像要延迟30s以上才接收到，然后延迟积累的tick逐渐在4分钟内快放完，之后延时才恢复正常，不知道是什么原因呢。

之前用qa的docker服务的时候也出现过这问题，还以为是订阅的全市场tick多，或者rabbitmq的问题导致，所以切换到这个项目自己搭建。

**Comment by somewheve** [comment]
这个我没遇到过哎  你是用实盘的行情服务器麻 以及你的是不是提前10分钟启动
