### ISSUE TITLE
多品种算法单应该怎么写呢

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#200]
有点没有头绪，是不是应该开多个CtpBee实例对应不同的品种去下单？这里面有不少细节比如下单的时候监控目前持仓。

**Comment by somewheve** [comment]
支持多品种的 把行情隔离开起来  但是一个ctpbee只能分割多个品种

**Comment by LJingnan** [comment]
@somewheve 嗯嗯，在一个ctpbee里订阅多个品种，在on_tick写逻辑，如果有不同的处理，那就在on_tick里用if
