### ISSUE TITLE
on_trade回调是不是有问题，我下了一个单，on_trade调用了7、8次

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#201]
我唯一发现有区别的就是 is_local 这个字段，是不是 is_local =True才代表交易完成？

**Comment by somewheve** [comment]
on_trade你要知道这个是逐步成交的 比如说你发了一个100手的单子 但是你的对手方A可能只会发10手单子  那么他发了10手单子 可能会和你成交一次  返回一个成交单  这个成交数量为10  然后对方方B 也发了5手单子 和你成交了也会返回一个成交单 以此类推

**Comment by somewheve** [comment]
你是按照demo写的吗 ？  用pip版本 别用master分支的

**Comment by somewheve** [comment]
贴下代码吧

**Comment by somewheve** [comment]
确保你只下了一次单  以及只订阅了一个品种

**Comment by LJingnan** [comment]
@somewheve 为什么要确保只订阅一个品种，多品种下单的话要订阅多个品种分别下单呀，我只对一个品种下返回多个回报

**Comment by LJingnan** [comment]
`from ctpbee import CtpBee, CtpbeeApi
from ctpbee.constant import *
from ctpbee import Action
from ctpbee import RiskLevel

class SendOrder(object):
    def __init__(self, exchange, symbol):
        self.exchange = exchange
        self.symbol = symbol
        try:
            self.local_symbol = f"{self.symbol}.{self.exchange.value}"
        except AttributeError:
            self.local_symbol = f"{self.symbol}.{self.exchange}"
    def __repr__(self):
        return str(self.__dict__)

class DoubleMA(CtpbeeApi):
    def __init__(self, name):
        super().__init__(name)

        self.finished = 0

    def on_contract(self, contract: ContractData):
        if contract.local_symbol in ['cu2212.SHFE', 'cu2210.SHFE']:
            self.action.subscribe(contract.local_symbol)

    def on_tick(self, tick: TickData) -> None:
        """
        tick行情触发的时候会调用此函数，你可以通过print来打印它查看详情
        """
        local_symbol = 'cu2212.SHFE'
        if self.finished == 0:
            send_order = SendOrder(exchange=local_symbol.split('.')[1], symbol=local_symbol.split('.')[0])
            ret = self.action.buy(61000, volume=1, price_type=OrderType.LIMIT,
                                  origin=send_order)
            self.finished = 1

    def on_trade(self, trade: TradeData) -> None:
        print(f"成交回报：{trade}")


app = CtpBee("ctpbee", __name__)  # 在此处我们创建我们的核心App。
info = {
  
    },
    "INTERFACE": "ctp",  # 接口声明
    "TD_FUNC": True,  # 开启交易功能
}
app.config.from_mapping(info)
double_ma = DoubleMA("double_ma")  # 创建我们的策略实例
app.add_extension(double_ma)  # 将我们的策略通过app的add_extension接口加入进系统
app.start()`

**Comment by LJingnan** [comment]
`
from ctpbee import CtpBee, CtpbeeApi
from ctpbee.constant import *
from ctpbee import Action
from ctpbee import RiskLevel

class SendOrder(object):
    def __init__(self, exchange, symbol):
        self.exchange = exchange
        self.symbol = symbol
        try:
            self.local_symbol = f"{self.symbol}.{self.exchange.value}"
        except AttributeError:
            self.local_symbol = f"{self.symbol}.{self.exchange}"
    def __repr__(self):
        return str(self.__dict__)

class DoubleMA(CtpbeeApi):
    def __init__(self, name):
        super().__init__(name)

        self.finished = 0

    def on_contract(self, contract: ContractData):
        if contract.local_symbol in ['cu2212.SHFE', 'cu2210.SHFE']:
            self.action.subscribe(contract.local_symbol)

    def on_tick(self, tick: TickData) -> None:
        """
        tick行情触发的时候会调用此函数，你可以通过print来打印它查看详情
        """
        local_symbol = 'cu2212.SHFE'
        if self.finished == 0:
            send_order = SendOrder(exchange=local_symbol.split('.')[1], symbol=local_symbol.split('.')[0])
            ret = self.action.buy(61000, volume=1, price_type=OrderType.LIMIT,
                                  origin=send_order)
            self.finished = 1

    def on_trade(self, trade: TradeData) -> None:
        print(f"成交回报：{trade}")


app = CtpBee("ctpbee", __name__)  # 在此处我们创建我们的核心App。
info = {
    "CONNECT_INFO": {
        "userid": "089131",
        "password": "350888",
        "brokerid": "9999",
        "md_address": "tcp://218.202.237.33:10112",
        "td_address": "tcp://218.202.237.33:10102",
        "product_info": "",
        "appid": "simnow_client_test",
        "auth_code": "0000000000000000"
    },
    "INTERFACE": "ctp",  # 接口声明
    "TD_FUNC": True,  # 开启交易功能
}
app.config.from_mapping(info)
double_ma = DoubleMA("double_ma")  # 创建我们的策略实例
app.add_extension(double_ma)  # 将我们的策略通过app的add_extension接口加入进系统
app.start()
`

**Comment by LJingnan** [comment]
这是代码

from ctpbee import CtpBee, CtpbeeApi
from ctpbee.constant import *
from ctpbee import Action
from ctpbee import RiskLevel

class SendOrder(object):
    def __init__(self, exchange, symbol):
        self.exchange = exchange
        self.symbol = symbol
        try:
            self.local_symbol = f"{self.symbol}.{self.exchange.value}"
        except AttributeError:
            self.local_symbol = f"{self.symbol}.{self.exchange}"
    def __repr__(self):
        return str(self.__dict__)

class DoubleMA(CtpbeeApi):
    def __init__(self, name):
        super().__init__(name)

        self.finished = 0

    def on_contract(self, contract: ContractData):
        if contract.local_symbol in ['cu2212.SHFE', 'cu2210.SHFE']:
            self.action.subscribe(contract.local_symbol)

    def on_tick(self, tick: TickData) -> None:
        """
        tick行情触发的时候会调用此函数，你可以通过print来打印它查看详情
        """
        local_symbol = 'cu2212.SHFE'
        if self.finished == 0:
            send_order = SendOrder(exchange=local_symbol.split('.')[1], symbol=local_symbol.split('.')[0])
            ret = self.action.buy(61000, volume=1, price_type=OrderType.LIMIT,
                                  origin=send_order)
            self.finished = 1

    def on_trade(self, trade: TradeData) -> None:
        print(f"成交回报：{trade}")


app = CtpBee("ctpbee", __name__)  # 在此处我们创建我们的核心App。
info = {

}
app.config.from_mapping(info)
double_ma = DoubleMA("double_ma")  # 创建我们的策略实例
app.add_extension(double_ma)  # 将我们的策略通过app的add_extension接口加入进系统
app.start()

**Comment by somewheve** [comment]
你有仔细看文档吗   0.0

**Comment by somewheve** [comment]
你先订阅单个品种测试一下回单触发多少次  以及用快期看看你的发单情况    

还有就是登陆的第一次 初期这个地方可能会回单很多次  因为有查询交易订单情况

**Comment by LJingnan** [comment]
@somewheve emmm仔细看了的，http://docs.ctpbee.com/modules/strategy.html，文档比较轻量，请问有么有比较详细的资料呀

“初期这个地方可能会回单很多次 因为有查询交易订单情况”好像是的。

所以如果我要辨认是不是真的成交回报，要用 is_local 嘛，因为我想在on_trade加个合约锁，上次的单未成交无法再次下单

**Comment by somewheve** [comment]
用init来判断是否初始化好  你要开动脑袋

**Comment by somewheve** [comment]
我不是给了on_init的吗 
正常来说 你下一手单 只会给一次回报的

**Comment by LJingnan** [comment]
@somewheve 谢谢谢谢，看来还是init的问题
