### ISSUE TITLE
如何在开盘时候尽快启动程序

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#202]
您好，我想在开盘马上开启多品种的算法交易，我发现类似cover这种平仓指令需要检查目前的持仓，导致策略需要等待on_init执行完毕（这时候获得了初始持仓），问题是获取初始持仓这个事情可能会比较慢，tick已经开始推了持仓还没返回，有没有什么办法可以提前让策略on_init，等到开盘的时候，马上接受tick开始下单呢

**Comment by LJingnan** [comment]
或者我手动输入现在的持仓，这个如何实现呀

**Comment by somewheve** [comment]
我不是给了hickey吗  有个infront参数 开盘前多少时间启动 

如果已经是进入盘中了 就别想了  不管怎么做都会少tick

**Comment by somewheve** [comment]
开盘前 app.start() 或者 开盘前hickey.start_all

**Comment by LJingnan** [comment]
@somewheve  谢谢
1、开盘前start的话，是不是会收到一些脏的tick，这个逻辑要额外处理？所以我现在想的方法是开盘前start但是不订阅合约，开盘后立马订阅合约让on_tick开始
2、“已经是进入盘中了 就别想了 不管怎么做都会少tick”，感觉不太一定，如果本地存好了目前的账户持仓，其实不需要等待on_init去拿持仓

**Comment by somewheve** [comment]
开盘前tick需要做一个过滤判断 ctp是脏tick的  

我说的是盘中会少tick的问题   启动再快都有一个过程

**Comment by LJingnan** [comment]
谢谢！
