### ISSUE TITLE
文档数据结构英汉对应

### ISSUE THREAD

**Issue by yangdemin** [ctpbee/ctpbee#203]
ask_price_1 | 买一价
bid_price_1 | 卖一价

///申卖价一
TThostFtdcPriceType	AskPrice1;

您的文档和代码里面的注释怎么不一样

**Comment by somewheve** [comment]
啊 我可能写反了 不好意思 。。。。。 我晚点修正下

**Comment by somewheve** [comment]
fixed with https://github.com/ctpbee/ctpbee_tutorial/commits/master
