### ISSUE TITLE
on_realtime 函数调用后 整个程序直接结束

### ISSUE THREAD

**Issue by yangdemin** [ctpbee/ctpbee#206]
on_realtime
Connect to 180.168.146.187:10201
Session 2105278465 Connected
2022-10-31 15:47:08 daily_task     INFO  daily_task   行情服务器连接成功
2022-10-31 15:47:082022-10-31 15:47:08 daily_task daily_task          INFOINFO    daily_taskdaily_task      交易连接成功行情服务器登录成功

2022-10-31 15:47:08 daily_task     INFO  daily_task   交易服务器验证成功
2022-10-31 15:47:08 daily_task     INFO  daily_task   交易登录成功

=========================
然后程序就结束了

**Comment by somewheve** [comment]
你自己写错东西了吧  贴下源代码

**Comment by yangdemin** [comment]
好的，源码有点多，我整理一下

**Comment by yangdemin** [comment]
_sim_test = {
            "userid": "201425",
            "password": "BGTbgt54321@",
            "brokerid": "9999",

            "td_address": "tcp://180.168.146.187:10201",
            "md_address": "tcp://180.168.146.187:10211",

            "appid": "simnow_client_test",
            "auth_code": "0000000000000000",
            "product_info": "0000000000000000",
}

def prepare_ctp_api(cfg):
    app = CtpBee(_strategy_name, __name__, refresh=True)
    app.config.from_mapping({
        "CONNECT_INFO": ctp_cfg_sim_test, #ctp_cfg_tts_test,ctp_cfg_zt_test,ctp_cfg_real_zt
        "INSTRUMENT_INDEPEND": True,
        "INTERFACE": "ctp",  # 接口声明
        "TD_FUNC": True,  # 开启交易功能
        "MD_FUNC": True,
        "XMIN": [1],
        "LOG_OUTPUT":True
    })

    strategy = HsCtpApi(_strategy_name, app, cfg)
    app.add_extension(strategy)
    app.start()
    return strategy

**Comment by somewheve** [comment]
额  不推荐start之后再返回了  推荐返回app 然后在外层 .start()

然后你装的版本是 哪个版本 ？ pip安装的？

**Comment by yangdemin** [comment]
ctpbee  :1.5.2 
 我是下载的ctpbee, ctpbee_api 到本地，运行的。
因为 dll 版本的原因，需要重新编译pyd文件

**Comment by somewheve** [comment]
感觉信息还不太够。。。    你看看能不能传一个完整的demo吧

**Comment by yangdemin** [comment]
我找到原因了，是生成的pyd 文件与dll 不匹配导致的。感谢你的回复

**Comment by somewheve** [comment]
ok的  。。。
