### ISSUE TITLE
20221226早上无法取得持仓

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#212]
20221226，早上开盘调仓，发现一直无法取得目前持仓（因为我需要得到当前持仓然后做轧差），导致程序一直卡住

**Comment by somewheve** [comment]
有更新最新版本的ctpbee吗

**Comment by LJingnan** [comment]
@somewheve 没哎，要更新麽

**Comment by somewheve** [comment]
如果你没有用risk level的话 是可以更新的  应该是无痛的

**Comment by LJingnan** [comment]
@somewheve 谢谢，更新后没问题哈
