### ISSUE TITLE
更新之后，合约查询的顺序逻辑好像改变了

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#213]
2022-12-26 20:43:58 demo     INFO  demo   合约信息查询成功

通常为了保证在交易前ctp已经返回了持仓，我在on_init里面添加了 self.app.mark_on_init=1以此来判断是否已经运行完on_init，在更新前，on_init的运行保证了合约信息查询成功，但是现在好像逻辑发生了改变。

**Comment by somewheve** [comment]
你现在查不到持仓了 ？ 在触发on_init之后

**Comment by LJingnan** [comment]
@somewheve 是的，不能马上查到，以前是没问题的。要再等一段时间，这就意味着我不能用on_init确认已返回持仓了

**Comment by LJingnan** [comment]
@somewheve 大佬有什么解决办法嘛

**Comment by LJingnan** [comment]
![image](https://user-images.githubusercontent.com/43166853/209739338-57e9492b-40be-4c89-916e-81b6e974bb59.png)
您看执行顺序

**Comment by somewheve** [comment]
我昨晚阳性超级难受 看到了没回  我今天看看把 稍等哈 我没注意这个

**Comment by somewheve** [comment]
```
    def _running(self, logout=True):
        """
        根据当前配置文件下的信息载入行情api和交易api
        注意此函数同时会根据构造函数中的refresh参数决定开启定时线程, 向CtpBee里面提供定时查询账户持仓功能
        """
        show_me = graphic_pattern(__version__, self.engine_method)
        if logout:
            print(show_me)
        self.init_interface()
        if self.config["PATTERN"] == "real" and self.r is None:
            sleep(1)
            self.r = Thread(target=refresh_query,
                            args=(self, common_signals, self.refresh,), daemon=False)
            self.r.start()
        else:
            pass
```
我以为有sleep1s后再开启查询的  估计是这个原因了 你试试sleep1s   这个在app.py

**Comment by LJingnan** [comment]
@somewheve 感谢阳了还回答消息！注意多休息，我也刚杨康。但好像加sleep(1)这个做法不work呀，还是init之后没拿到持仓

**Comment by somewheve** [comment]
啊 到底是合约没拿到还是持仓没拿到 尴尬  


你确认下信息

**Comment by LJingnan** [comment]
@somewheve 
是持仓没拿到哈。肯定是有持仓的，因为是实盘账户。相当于：
init显示运行了，我调用持仓app.center.positions，返回空list。

得过一段时间，console才会提示返回持仓成功，这时候调用app.center.positions才有结果

所以问题是init调用的时候，交易所还没有返回持仓

**Comment by somewheve** [comment]
我再看看代码

**Comment by somewheve** [comment]
这次升级的造成不便 不好意思哈  

你看下td_api.py  
```
    def onRspQryTradingAccount(self, data: dict, error: dict, reqid: int, last: bool):
        """"""
        account = AccountData(
            accountid=data["AccountID"],
            balance=data["Balance"],
            frozen=data["FrozenMargin"] +
                   data["FrozenCash"] + data["FrozenCommission"],
            gateway_name=self.gateway_name
        )
        account.available = data["Available"]
        self.on_event(type=EVENT_ACCOUNT, data=account)
        if self.instrunment_init_flag and self.position_init_flag and not self.init_status:
            self.reqid += 1
            self.init_status = True
            self.reqQryDepthMarketData({}, self.reqid)
            self.on_event(type=EVENT_INIT_FINISHED, data=True)
```
替换这个函数试试

**Comment by LJingnan** [comment]
@somewheve 0 0, 好像还是不行，我用print确保了我修改的是对的函数。

**Comment by somewheve** [comment]
能远程支持下吗  尴尬

**Comment by LJingnan** [comment]
`
from ctpbee import CtpbeeApi, CtpBee
info = {

}
app = CtpBee(name="demo", import_name=__name__, refresh=True)
# demo策略，什么也不做
class CtpbeeApi_demo(CtpbeeApi):
    def on_init(self, init: bool) -> None:  # 改写on_init, 在on_init激活的时候打印
        self.app.mark_on_init = 1
        print(f"!!!!!!!!!! init :{init}")
        positions = app.center.positions
        print(f'持仓：{positions}')   # 如果这个print是空list，说明init后仍然没有持仓

app_demo = CtpbeeApi_demo('demo')

app.add_extension(app_demo)  
app.config.from_mapping(info) 


app.start(log_output=True)
positions = app.center.positions
while len(positions) == 0 :
    positions = app.center.positions
print(f"当前持仓：{positions}")
'''
输出：
2022-12-29 22:59:38 demo     INFO  demo   交易连接成功
2022-12-29 22:59:38 demo     INFO  demo   行情服务器连接成功
2022-12-29 22:59:38 demo     INFO  demo   交易服务器验证成功
2022-12-29 22:59:38 demo     INFO  demo   行情服务器登录成功
2022-12-29 22:59:38 demo     INFO  demo   交易登录成功
2022-12-29 22:59:39 demo     INFO  demo   结算信息确认成功
!!!!!!!!!! init :True
持仓：[]    # 说明 init 后仍然没有持仓
2022-12-29 22:59:53 demo     INFO  demo   合约信息查询成功

'''
`
@somewheve  我写了个demo哈，是最新版的ctpbee

**Comment by LJingnan** [comment]
`
from ctpbee import CtpbeeApi, CtpBee
info = {

}
app = CtpBee(name="demo", import_name=__name__, refresh=True)
class CtpbeeApi_demo(CtpbeeApi):
    def on_init(self, init: bool) -> None:  # 改写on_init, 在on_init激活的时候打印
        self.app.mark_on_init = 1
        print(f"!!!!!!!!!! init :{init}")
        positions = app.center.positions
        print(f'持仓：{positions}')   # 如果这个print是空list，说明init后仍然没有持仓

app_demo = CtpbeeApi_demo('demo')

app.add_extension(app_demo)
app.config.from_mapping(info)


app.start(log_output=True)
positions = app.center.positions
while len(positions) == 0 :
    positions = app.center.positions
print(f"当前持仓：{positions}")
'''
输出：
2022-12-29 22:59:38 demo     INFO  demo   交易连接成功
2022-12-29 22:59:38 demo     INFO  demo   行情服务器连接成功
2022-12-29 22:59:38 demo     INFO  demo   交易服务器验证成功
2022-12-29 22:59:38 demo     INFO  demo   行情服务器登录成功
2022-12-29 22:59:38 demo     INFO  demo   交易登录成功
2022-12-29 22:59:39 demo     INFO  demo   结算信息确认成功
!!!!!!!!!! init :True
持仓：[]    # 说明 init 后仍然没有持仓
2022-12-29 22:59:53 demo     INFO  demo   合约信息查询成功

'''
`
@somewheve 我写了个demo哈

**Comment by LJingnan** [comment]
`from ctpbee import CtpbeeApi, CtpBee
info = {

}
app = CtpBee(name="demo", import_name=__name__, refresh=True)
class CtpbeeApi_demo(CtpbeeApi):
    def on_init(self, init: bool) -> None:  # 改写on_init, 在on_init激活的时候打印
        self.app.mark_on_init = 1
        print(f"!!!!!!!!!! init :{init}")
        positions = app.center.positions
        print(f'持仓：{positions}')   # 如果这个print是空list，说明init后仍然没有持仓

app_demo = CtpbeeApi_demo('demo')

app.add_extension(app_demo)
app.config.from_mapping(info)


app.start(log_output=True)
positions = app.center.positions
while len(positions) == 0 :
    positions = app.center.positions
print(f"当前持仓：{positions}")`

**Comment by somewheve** [comment]
@LJingnan 你能加下群 467026334

**Comment by somewheve** [comment]
![d207b8f961bff6d45b17890806e4f6d](https://user-images.githubusercontent.com/29819669/210046666-a9c95835-ccc1-4045-828c-74752fe47404.jpg)

@LJingnan  进群聊

**Comment by somewheve** [comment]
this error fixed by https://github.com/ctpbee/ctpbee/commit/46184905572328d1254d52c55778526923ded550
