### ISSUE TITLE
ctpbee 1.5.5，启动报错`AttributeError: NONE

### ISSUE THREAD

**Issue by ganyu21** [ctpbee/ctpbee#215]
最新ctp 1.5.5，启动报错

`AttributeError: NONE

At:
  C:\Users\xxx\.conda\envs\env_python37\lib\enum.py(354): __getattr__
  C:\Users\xxx\.conda\envs\env_python37\lib\site-packages\ctpbee\interface\ctp\md_api.py(93): onRtnDepthMarketData`

**Comment by somewheve** [comment]
升级到最新的ctpbee即可

**Comment by ganyu21** [comment]
嗯，看到了，谢谢
