### ISSUE TITLE
实盘技术支持

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#217]
由于作者过于怠惰.,  仅对实盘用户提供有限技术支持，帮助排查实盘过程中遇到的问题，优化实盘体验。 

如需支持, 请发送邮件至 somewheve@gmail.com，我会发微信二维码给你， 注意仅仅只接受实盘用户。

同时可以在社区寻求支持， 请前往 [forum.ctpbee.com](http://forum.ctpbee.com) 

。

**Comment by hxhrtrading** [comment]
ok
