### ISSUE TITLE
“平昨仓位不足”应该怎么处理？

### ISSUE THREAD

**Issue by ganyu21** [ctpbee/ctpbee#218]
请问一下，我这边提示
`'ErrorID': 51, 'ErrorMsg': 'CTP:平昨仓位不足', 'detail': '交易委托失败`
应该怎么处理

我在仿真测试上期所的螺纹钢，仓位有足的，看ctpbee文档介绍，buy_close和sell_close均会自动平今和平昨，那为什么还会出现平昨仓位不足？

**Comment by somewheve** [comment]
1. 仿真测试如果是期货公司的仿真测试可能就出很奇怪的问题 
2. 也有可能是当前仓位被锁住（你的仓位已经发送出去平仓单但是没有成交 ） 此时是无法进行平仓的 

综上所述 推荐1.先cancel-all全部订单再进行平仓操作 
2，使用simnow环境测试交易接口的稳定性 据我所知实盘用户基本不会遇到这个问题

**Comment by ganyu21** [comment]
使用的是simnow，我试试用cancel-all

**Comment by somewheve** [comment]
self.action.cancel_all()

**Comment by somewheve** [comment]
测试是否ok？  如果验证可以 那我关掉issue了

**Comment by ganyu21** [comment]
设置self.action.cancel_all有效果，非常感谢！
