### ISSUE TITLE
INTERFACE 的参数值ctp_se不存在

### ISSUE THREAD

**Issue by ganyu21** [ctpbee/ctpbee#221]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/25415784/211233596-bb0e1b48-0c41-4299-8986-66c9c7a404b3.png">

如文档，设置为ctp_se，提示“错误参数”
那么现在“穿透式申请”是否只要设置为“ctp”即可

**Comment by somewheve** [comment]
文档稍后更新  目前来说填ctp 然后自己修改ctpbee_api的源代码  晚点我会写个教程

**Comment by somewheve** [comment]
http://forum.ctpbee.com/d/2-qi-huo-ctpchuan-tou-ce-shi-jiao-cheng 
你可以看看此信息

**Comment by ganyu21** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/25415784/211237753-8c1ac2bf-7de7-456c-b946-5d1fd9b5a307.png">

有两点疑问
1、期货公司给的测试API，一般需要用他们给的接口api去覆盖ctp的dll和so，这里面的原因是期货公司的测试API版本问题吗？
目前期货公司给的测试API是6.3.19
2、期货公司的环境测试完后，按文档要求是卸除重装，这是因为目前ctpbee安装带的api对实盘的版本是支持的原因，所以不需要继续用期货公司给的api吗？

**Comment by somewheve** [comment]
期货公司测试的API是 是特殊版本的 例如你的6.3.19 我的实盘API版本是6.6.1 不一样的， 目前ctpbee API只有实盘稳定的API

**Comment by ganyu21** [comment]
进入到ctpbee_api目录
`pip install -e .`
运行报错
`ERROR: file:///C:/Users/xxx/.conda/envs/env_python37/Lib/site-packages/ctpbee_api does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by somewheve** [comment]
不是让你下完之后再 执行这个 先把ctpbee_api卸载了  然后去下载ctpbee_api的源代码  然后cd到那个目录

**Comment by somewheve** [comment]
那你就不需要pip install -e .  

直接填ctp交易测试即可

**Comment by ganyu21** [comment]
我这边1.5.7，无论是替换了dll和lib，还是没有替换，链接期货公司的仿真测试环境均获取不到合约，我订阅的是rb2305，但没有得到合，显示
`local_symbol=.CFFEX`

**Comment by somewheve** [comment]
我这边遇到同样的问题 换了他们的仿真交易环境就好了  用实盘API 你去问问他们的技术人员。

**Comment by somewheve** [comment]
他们的仿真测试环境 可能和我的API不兼容  不确定
