### ISSUE TITLE
23.02.24 macos下，dev版本启动成功后1s内核立刻挂掉

### ISSUE THREAD

**Issue by Wilson-G** [ctpbee/ctpbee#231]
感谢更新支持mac系统，但是登陆成功以后出现了以上的问题，且没有弹出任何的提示内核就挂掉跳出了

**Comment by somewheve** [comment]
我暂时还没找到那个问题

**Comment by somewheve** [comment]
这阵子要搞策略的所以没时间搞那个。感觉很奇怪内存问题 同样编译生成的代码 windows是可以跑的

**Comment by somewheve** [comment]
我看下vnctp的 应该是我link错了

**Comment by somewheve** [comment]
好像是mac下面的头文件需要不一样的。。。 
我也看不懂  明天改下试试

**Comment by Wilson-G** [comment]
好滴，期待一下

**Comment by somewheve** [comment]
签名都改了擦。我要花点时间搞搞

**Comment by somewheve** [comment]
```
	//Mac版本的登录函数多了两个参数
	#ifndef __APPLE__
		int i = this->api->ReqUserLogin(&myreq, reqid);
	#else
		int i = this->api->ReqUserLogin(&myreq, reqid, 2, "vn");
	#endif
``` 
靠

**Comment by Wilson-G** [comment]
弄咋样了？

**Comment by somewheve** [comment]
改动有点多 需要点时间 我也很无语0.0

**Comment by somewheve** [comment]
我在dev提交了最新的代码 但是在我自己本地代码过不去 你试试编译一下 @Wilson-G  我的系统是m2 芯片 然后系统更新到 13.1了。运行一会就有dbus问题

**Comment by Wilson-G** [comment]
更新到最新代码，然后重新编译安装了，出现以下错误

File ~/Documents/ctpbee_api/ctpbee_api/ctp/__init__.py:1, in <module>
----> 1 from .vnctpmd import MdApi
      2 from .vnctptd import TdApi
      3 from .ctp_constant import *

ImportError: dlopen(/Users/wil/Documents/ctpbee_api/ctpbee_api/ctp/vnctpmd.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '__ZN15CThostFtdcMdApi13GetApiVersionEv'

**Comment by somewheve** [comment]
我是复制vnpy的代码哎  0.0

**Comment by somewheve** [comment]
我再试试把 。。。

**Comment by Wilson-G** [comment]
老哥加油，给你打call

**Comment by somewheve** [comment]
mac我修复成功了 但是过程有点复杂  需要配置到lib库 感觉很奇怪

**Comment by somewheve** [comment]
参见[此处README](https://github.com/ctpbee/ctpbee_api), 于0.43发布

**Comment by somewheve** [comment]
已经修复此问题 如果后续还有问题请开一个新的issue， 我这边是能正常运行了 如何安装参考ctpbee_api
