### ISSUE TITLE
交易日2023  04-03 04-04 出错 

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#237]
这两天强制启动把

**Comment by somewheve** [comment]
应该是由米筐那边生成的交易日导致的 我这边一开始从yutiansut 那边拿的

**Comment by nyg2017** [comment]
话说楼主能不能share下这两天的数据。依赖CTPbee接数据，刚刚check了下，这两天确实没接到。

**Comment by nyg2017** [comment]
感谢楼主，之前写了，又怕不妥所以就删了。坐等楼主share 个百度云链接。缺了这两天贼难受，还在想从哪儿找数据对齐的事儿。

**Comment by d-zh** [comment]
同求04-03和04-04的tick数据

**Comment by somewheve** [comment]
链接：https://pan.baidu.com/s/1GTLIUCwhQSsfFFhn5MVPHg 
提取码：hmku 

tqsdk的数据  你记得切换下数据结构

**Comment by nyg2017** [comment]
感谢楼主
