### ISSUE TITLE
什么版本能正常安装

### ISSUE THREAD

**Issue by ethonchen** [ctpbee/ctpbee#238]
我试了
ubuntu18.03 python 3.10.10 gcc 6 
ubuntu18.03 python 3.10.10 gcc 9 
ubuntu23.03 python 3.11.2 gcc 12.2
都不能正常安装。 下面是 ubuntu23.03 报错。。

      /usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ctpbee_api

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(.venv) root@ad80e40872c7:/qihuo/ctpbee# truct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
bash: truct: command not found
bash: syntax error near unexpected token `|'
bash: error:: command not found
bash: [end: command not found

**Comment by somewheve** [comment]
按理来说3.10 应该是可以的啊
3.11不确定 有没有更加详细的

**Comment by ethonchen** [comment]
我试试，刚改成gcc 9.5也不行 。现在是 ubuntu23.03 python 3.11.2 gcc 9.5 。我试试python3.10 
或者告诉我一个肯定可以install成功的版本

creating build/temp.linux-x86_64-cpython-311/ctpbee_api/ctp/vnctp/vnctpmd
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Ictpbee_api/ctp/vnctp -Ictpbee_api/ctp/include -I/qihuo/ctpbee/.venv/include -I/usr/include/python3.11 -c ctpbee_api/ctp/vnctp/vnctpmd/vnctpmd.cpp -o build/temp.linux-x86_64-cpython-311/ctpbee_api/ctp/vnctp/vnctpmd/vnctpmd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare -pthread
      In file included from ctpbee_api/ctp/include/pybind11/cast.h:16,
                       from ctpbee_api/ctp/include/pybind11/attr.h:13,
                       from ctpbee_api/ctp/include/pybind11/pybind11.h:43,
                       from ctpbee_api/ctp/vnctp/vnctp.h:14,
                       from ctpbee_api/ctp/vnctp/vnctpmd/vnctpmd.h:6,
                       from ctpbee_api/ctp/vnctp/vnctpmd/vnctpmd.cpp:4:
      ctpbee_api/ctp/include/pybind11/detail/internals.h: In function ‘pybind11::detail::internals& pybind11::detail::get_internals()’:
      ctpbee_api/ctp/include/pybind11/detail/internals.h:194:27: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]
        194 |         PyEval_InitThreads();


      ctpbee_api/ctp/include/pybind11/pybind11.h:1895:30: note: in expansion of macro ‘PyTuple_GET_ITEM’
       1895 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
            |                              ^~~~~~~~~~~~~~~~
      /usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ctpbee_api

note: This is an issue with the package mentioned above, not pip.

**Comment by somewheve** [comment]
装个3.9试试

**Comment by ethonchen** [comment]
我换成3.9.16就可以了。。果然3.10 3.11都不行

**Comment by ethonchen** [comment]
多谢，可以close了 。建议把版本要求贴一下

**Comment by somewheve** [comment]
不是 不清楚3.11发生啥改变了  3.10 上面我也不懂了

**Comment by ethonchen** [comment]
装是装好了，但是连simnow报错了。运行example的代码
python send_order_demo.py

2023-04-07 21:03:18 rohon_test     INFO  rohon_test   交易连接成功
2023-04-07 21:03:18 rohon_test     INFO  rohon_test   行情服务器连接成功
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

**Comment by ethonchen** [comment]
语言包的问题吗，
运行 sudo ctpbee -auto generate
提示 ：sh: 1: locale-gen: not found

运行 export LC_ALL="C"
还是同样报错

**Comment by somewheve** [comment]
你这个是啥系统 可能不支持  locale-gen 找下替换品

**Comment by ethonchen** [comment]
是的，ubuntu23.04 缺少依赖库
你的标准环境是啥。我参考一下免得后面还遇到奇奇怪怪的事情

**Comment by somewheve** [comment]
哈  需要生成中文支持环境 错误信息很明显 找下替代品就好了

**Comment by somewheve** [comment]
没啥标准环境 搞完这个就好了

**Comment by somewheve** [comment]
哈 我不是已经更新了依赖了吗  现在还是装不了吗

**Comment by qm13579** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by somewheve** [comment]
贴报错信息

**Comment by somewheve** [comment]
估计是gcc版本不行 不兼容那个pybind11
