### ISSUE TITLE
无法触发bar数据

### ISSUE THREAD

**Issue by ZhangRicky** [ctpbee/ctpbee#240]
好像无法触发分钟bar数据的回调函数吧，烦请大佬给予帮助

**Comment by ZhangRicky** [comment]
复写on_bar（）函数，没有触发函数的调用，请指教

**Comment by somewheve** [comment]
该项目不咋做维护了 太忙了 搞完后再来修复问题了  推荐你去找个生成k线的代码 把on_tick的tick数据传进去 或者使用其他的量化框架作为替代品 。

**Comment by somewheve** [comment]
搞完回来了 这两天来开始update

**Comment by somewheve** [comment]
k线触发现在参照readme里面描述的
