### ISSUE TITLE
对交易和行情在触发上的独立性的咨询

### ISSUE THREAD

**Issue by shenqixue** [ctpbee/ctpbee#244]
1，对于同一个类生成的不同实例，其on tick和on order这些是不是独立触发？比方说我用同一个类生成两个实例，交易不同的合约，两个会不会相互混淆？
2，如果在同一个文件中定义两个不同的子类，根据两个子类生成两个实例，这两个实例的独立性如何？
3，配置项里面INSTRUMENT_INDEPEND参数似乎是解决独立性的问题，是用来解决我所说的第1种情形吗？

**Comment by somewheve** [comment]
你的第一个问题同一个类生产的 你调用了`__init__`,  那么他在内存中是唯一的。  
然后现在并不是谁发的就回调给谁，  至少目前没有实现这个比较复杂的功能， 
INSTRUMENT_INDEPEND 是实现合约的独立处理。  比如说ag2310发的单 只会回调给拥有ag2310.SHFE代码的实例。
