### ISSUE TITLE
buy和sell这些函数，是不是没有办法发送FAK订单？

### ISSUE THREAD

**Issue by shenqixue** [ctpbee/ctpbee#245]

**Comment by shenqixue** [comment]
还有，我发现buy和sell里面似乎没法填合约代码，那么我在主力合约的触发里面，对非主力合约进行交易如何实现？我是套利的。不好意思，问题有点多，之前都是用第三方软件交易，没有自己开发过ctp

**Comment by somewheve** [comment]
buy和sell是高级函数， 需要你通过传tick 或者order或者bar进行，可以通过`price_type`参数进行指定， 建议查看函数签名。 

然后套利这个 ctpbee是提高最基础的交易框架 并没有实现高级的抽象， 你可以自己想办法写下 无非是根据时间戳进行对齐 然后再进行交易，
