### ISSUE TITLE
执行 examples/send_order_demo.py 报错

### ISSUE THREAD

**Issue by xiefengnian** [ctpbee/ctpbee#252]
[134:IOT] ⬢ [envd]❯ /usr/bin/python3 /home/envd/ctpbee-dev/demo.py
                                                            
               @             @                           
                )           (                                 
            #####################                               
          ##                     ##                            
         ##                       ##                                                  
        ##   ctpbee   :1.6.1       ##                          
        ##                         ##                          
        ##   engine   :thread      ##                          
         ##                       ##                          
          ++++++++    +    ++++++++                      
       (|||||||||| + +++ + ||||||||||)                          
          +++++++ +++++++++ +++++++                            
                   +++++++
                      T                                        
        
2023-11-20 13:32:16 demo     INFO  demo   行情服务器连接成功
qemu: uncaught target signal 6 (Aborted) - core dumped
[1]    12005 abort      /usr/bin/python3 /home/envd/ctpbee-dev/demo.py

**Comment by somewheve** [comment]
qemu 是啥  0.0  不是正常的linux内核吗

**Comment by somewheve** [comment]
这种使用模拟器的 我不确定哈 没有对这个做支持。这个issue关闭哈
