### ISSUE TITLE
请问现在是否支持获取历史数据

### ISSUE THREAD

**Issue by bob-lytton** [ctpbee/ctpbee#261]
刚开始用这个框架，想了解一下ctpbee现在是否已经支持某种获取历史数据的方式。

我看了下CTP的API，里面似乎是没有提供历史数据的获取或者订阅接口的，只有一个行情订阅接口可以获取实时数据。搜了下ctpbee这边文档里则没有提到历史数据相关的内容，issue里也只找到一个不支持获取历史数据的回答，但距离现在也已经有快一年了，想知道现在是否有新的进展呢？还是说仍然不支持？

**Comment by somewheve** [comment]
至于历史数据获取方式 可能需要你从tqsdk项目那边拿了

**Comment by somewheve** [comment]
或者你购买相关的历史数据也是可以的
