### ISSUE TITLE
获取持仓信息时候期权的头寸拿不到

### ISSUE THREAD

**Issue by isomorphicor** [ctpbee/ctpbee#265]
CtpbeeApi.center.positions 拿不到期权

**Comment by somewheve** [comment]
你打印下 app.recorder.positions 这个 看看里面有没有你的仓位

**Comment by isomorphicor** [comment]
也是空的
![Uploading image.png…]()

**Comment by somewheve** [comment]
你的图片好像看不到？  我这边显示看不到

**Comment by somewheve** [comment]
你在on_contract里面能打印下期权的头寸合约吗

**Comment by somewheve** [comment]
判断下symbol或者local_symbol

**Comment by isomorphicor** [comment]
![image](https://github.com/ctpbee/ctpbee/assets/12960324/2d9571a8-9241-467e-9616-c268c77ea998)
![image](https://github.com/ctpbee/ctpbee/assets/12960324/b859ba79-a637-412f-b1bd-c68ca2c27226)

**Comment by somewheve** [comment]
能否提供一个simnow的带期权的账户给我？

**Comment by isomorphicor** [comment]
我这个是实盘 simnow还没有

**Comment by isomorphicor** [comment]
我邮件给你实盘的

**Comment by somewheve** [comment]
别 哥 实盘不至于吧

**Comment by somewheve** [comment]
我晚上看看  稍等下  我今晚处理下 看看能不能搞定

**Comment by isomorphicor** [comment]
感谢

**Comment by somewheve** [comment]
@isomorphicor 我查了来这个仓位了 但是他和期货仓位一样 太诡异了

**Comment by somewheve** [comment]
你的ctpbee版本是1.x？   你更新下试试

**Comment by somewheve** [comment]
搞错了 没事了 我再研究研究

**Comment by isomorphicor** [comment]
> 你的ctpbee版本是1.x？ 你更新下试试

对1.5.7，我换成1.6.4之后对应的ctpbee_api也升级成了0.42，但发现on_bar函数触发有问题，然后用self.center.positions还是取不到哈。

1 . 是不是需要订阅？
2. 是不是需要用self.center.get_position(local_symbol) 指定具体合约代码才可以？

**Comment by isomorphicor** [comment]
constant 中的AccountData
是不是应该改成


class AccountData(Entity):
    """
    Account data contains information about balance, frozen and
    available.
    """
    local_account_id: str = ""
    accountid: str

    balance: float = 0
    frozen: float = 0
    available: float = 0

    def __post_init__(self):
        """"""
        # self.available = self.balance - self.frozen
        self.local_account_id = f"{self.gateway_name}.{self.accountid}"

**Comment by isomorphicor** [comment]
我发现问题了，是没有股指期货，只有商品期货

**Comment by isomorphicor** [comment]
解决方法如下：
interface.ctp.lib.py
加1行
PRODUCT_CTP2VT = {
    THOST_FTDC_PC_Futures: Product.FUTURES,
    THOST_FTDC_PC_Options: Product.OPTION,
    THOST_FTDC_PC_SpotOption: Product.OPTION
}

**Comment by isomorphicor** [comment]
但是仅有期权的account中balance还是不太对 @somewheve

**Comment by somewheve** [comment]
on_bar函数触发参见ctpbee_kline. 
只有一分钟的 暂时  
然后你会提pr吗   

这个balance是我从ctp那边查询回来的

**Comment by isomorphicor** [comment]
1. 包含期权的balance和不含权的不太一样，一个是市值，一个不包括期权价值，我理解有误哈
2. 不过  1.6.4相对于1.5.7问题在于  onRspQryTradingAccount函数account.available = data["Available"]没放在构造之外，导致轮询的时候available反复被重置为balance-frozen
```
        account = AccountData(
            accountid=data["AccountID"],
            balance=data["Balance"],
            frozen=data["FrozenMargin"] +
                   data["FrozenCash"] + data["FrozenCommission"],
            gateway_name=self.gateway_name
        )
        account.available = data["Available"]
```

**Comment by isomorphicor** [comment]
> 1. 包含期权的balance和不含权的不太一样，一个是市值，一个不包括期权价值，我理解有误哈
> 2. 不过  1.6.4相对于1.5.7问题在于  onRspQryTradingAccount函数account.available = data["Available"]没放在构造之外，导致轮询的时候available反复被重置为balance-frozen
> 
> ```
>         account = AccountData(
>             accountid=data["AccountID"],
>             balance=data["Balance"],
>             frozen=data["FrozenMargin"] +
>                    data["FrozenCash"] + data["FrozenCommission"],
>             gateway_name=self.gateway_name
>         )
>         account.available = data["Available"]
> ```

这两个都没问题的话，我提PR

**Comment by somewheve** [comment]
要放在里面

**Comment by somewheve** [comment]
那个Option的 我昨天推送到dev分支了  你记得往dev分支提交哈。 

这个available药放在里面进行构造把

**Comment by isomorphicor** [comment]
> 那个Option的 我昨天推送到dev分支了 你记得往dev分支提交哈。
> 
> 这个available药放在里面进行构造把

1.5.7放外面
1.6.4放里面了，但是因为每隔1秒左右会刷新center中的account，那个时候会反复初始化，导致重新计算available
![image](https://github.com/ctpbee/ctpbee/assets/12960324/f6c34c07-12f5-470b-975f-a17f54e391e2)

**Comment by somewheve** [comment]
理解了 

你提交pr吗 还是我改

**Comment by somewheve** [comment]
那我提交了 下个版本会修正

**Comment by isomorphicor** [comment]
> 那我提交了 下个版本会修正

嗯嗯，村里断网了，刚看到

**Comment by somewheve** [comment]
这个issue在新版本发布的时候会关掉哈

**Comment by somewheve** [comment]
已经修正如何还有问题 到时候再打开
