### ISSUE TITLE
通过ctpbee下单后，如果通过期货公司客户端成功平仓后，ctpbee的self.center.get_position仍然可以查到平仓前的仓位

### ISSUE THREAD

**Issue by ganyu21** [ctpbee/ctpbee#269]

**Comment by somewheve** [comment]
有没有代码  给出一个demo操作例子

**Comment by ganyu21** [comment]
我是在生产环境，ctpbee版本是1.6.5，self.action.buy_open或self.action.sell_open进行下单，几天后我通过期货公司app客户端成功平仓，但是self.center.get_position还是可以查询到仓位，感觉是有缓存，我重装了ctpbee仍然可以查到

**Comment by somewheve** [comment]
我测试下

**Comment by somewheve** [comment]
我需要晚上的时候追踪下，他这个7*24小时 好像不会让我成交的样子 没搞懂

**Comment by somewheve** [comment]
我复现问题了 确实下完单 不会更新本地仓位了 有点奇怪

**Comment by somewheve** [comment]
我明天白天修复下把

**Comment by somewheve** [comment]
我需要重新设计下仓位流程 等我哈

**Comment by ganyu21** [comment]
你好，有进展吗

**Comment by somewheve** [comment]
simnow账户能发给我嘛

**Comment by somewheve** [comment]
我的账户没下单权限了。

**Comment by somewheve** [comment]
你试试最新更新的master分支的 我测试是没问题的
