### ISSUE TITLE
连续主力合约的回测功能，能否开源呢

### ISSUE THREAD

**Issue by qingwg** [ctpbee/ctpbee#280]
此主力合约问题已经被解决 但是暂时不能开源  先关闭

_Originally posted by @somewheve in https://github.com/ctpbee/ctpbee/issues/32#issuecomment-716440497_
            
看到已经实现了，能否开源了，谢谢了

**Comment by somewheve** [comment]
这个被删掉了   兄弟能用还是用wondertrader或者vnpy吧
