### ISSUE TITLE
多账户之间缺少隔离

### ISSUE THREAD

**Issue by yilin-hust** [ctpbee/ctpbee#281]
当创建多个app（账户）时，日志输出的app.name永远是最后一个创建app的name
其次订单，交易等关键信息没有进行账户隔离：
account1的订单会推送到account2，account2的订单也会推送到account1，有时同一个订单会推送两次：
<img width="960" alt="1111111111111111" src="https://github.com/user-attachments/assets/b9296623-c33c-4e35-af4e-643bb02c7a9e">
<img width="1004" alt="2222222222" src="https://github.com/user-attachments/assets/75f0c7ad-4776-4f72-a266-227973dfd9e2">

**Comment by yilin-hust** [comment]
from ctpbee import CtpBee, CtpbeeApi
from ctpbee.constant import *


class DoubleMAMain(CtpbeeApi):
    def __init__(self, name):
        super().__init__(name)
        self.instrument_set = ['rb2501.SHFE']

    def on_contract(self, contract: ContractData):
        if contract.local_symbol in self.instrument_set:
            self.action.subscribe(contract.local_symbol)

    def on_tick(self, tick: TickData) -> None:
        print("tickMain:", self.app.name, tick)


class DoubleMASub(CtpbeeApi):
    def __init__(self, name):
        super().__init__(name)
        self.instrument_set = []

    def on_tick(self, tick: TickData) -> None:
        print("tickSub:", self.app.name, tick)


if __name__ == '__main__':

    app1 = CtpBee("account1", __name__)
    app1.config.from_json("config1.json")
    strategy = DoubleMAMain("DoubleMAMain")
    app1.add_extension(strategy)
    app1.start()

    app2 = CtpBee("account2", __name__)
    app2.config.from_json("config2.json")
    app2.add_extension(DoubleMASub("DoubleMASub"))
    app2.start()

**Comment by yilin-hust** [comment]
日志问题可修改Recorder的process_log_event等方法：
```
    def process_log_event(self, event: Event):
        self.logs[self.get_local_time()] = event.data
        if self.app.config.get("LOG_OUTPUT"):
            self.app.logger.info(event.data, owner="ctpbee", name=self.app.name)
```

**Comment by yilin-hust** [comment]
订单数据账户共享问题确实存在：
在td_api的onRtnOrder方法中增加打印：
`print('onRtnOrder:', self.userid, data)`
最终两个账户都收到了订单回调：
<img width="1614" alt="33333333" src="https://github.com/user-attachments/assets/4c6eba7a-f8f9-4171-b625-96d55c1cf46c">

**Comment by yilin-hust** [comment]
原因已找到，问题在于AppSignal构造方法中生成的随机数是重复的，不知道是否是mac操作系统的问题

**Comment by somewheve** [comment]
抱歉 回复有点慢

**Comment by somewheve** [comment]
给我点时间 我来查看下这个问题

**Comment by somewheve** [comment]
查看你当前用户目录下的ctpbee文件夹 ？ 

`ls ~/.ctpbee`

**Comment by yilin-hust** [comment]
嗯，之所以将订单回调放在Tool里面，原因是我只想一个账户进行行情订阅，不知这是否合理

**Comment by somewheve** [comment]
是那个Tool的处理的问题 机制没想好这里

**Comment by somewheve** [comment]
没做好分发的问题

**Comment by somewheve** [comment]
你也可以看看相关代码 如果你能早点想到办法 也是可以给我提交PR的

**Comment by somewheve** [comment]
我知道了  我修复下 tools应该放在实例里面进行初始化 这样是类里面的全局变量了

**Comment by yilin-hust** [comment]
去掉Tool，在策略中回调是OK的，问题是两个账户都必须订阅相关合约相关行情，如果合约数、账户数比较多的话，性能消耗有些大：

```
from ctpbee import CtpBee, CtpbeeApi, Tool
from ctpbee.constant import *


class Main(CtpbeeApi):
    def __init__(self, extension_name, app, **kwargs):
        super().__init__(extension_name, app, **kwargs)
        self.init = False
        self.ok = 0
        self.codes = ['ag2502.SHFE', 'ni2412.SHFE', 'rb2501.SHFE', 'p2501.DCE']

    def on_tick(self, tick: TickData) -> None:
        if self.init and self.ok == 0:
            print("tickMain:", self.app.name, tick)
            self.ok = 1

    def on_contract(self, contract: ContractData):
        if contract.symbol in self.codes:
            # print("--on_contract---", contract)
            self.action.subscribe(contract.local_symbol)

    def on_init(self, init: bool):
        print("on_initMain:", self.app.name, init)
        self.init = True

    def on_order(self, order: OrderData):
        print("-->>>>on_order", self.app.name, order.order_id, order.local_symbol, order.status)

    def on_trade(self, trade: TradeData):
        print("-->>>>on_trade", self.app.name, trade.order_id, trade.local_symbol)


if __name__ == '__main__':

    app1 = CtpBee("account1", __name__)
    app1.config.from_json("config1.json")
    app1.add_extension(Main("ExtensionMain", app=app1))
    # app1.add_tool(CallBackTool(name='CallBackMain', app=app1))
    app1.start()

    app2 = CtpBee("account2", __name__)
    app2.config.from_json("config2.json")
    app2.add_extension(Main("ExtensionSub", app=app2))
    # app2.add_tool(CallBackTool(name='CallBackSub', app=app2))
    app2.start()
```

**Comment by somewheve** [comment]
https://github.com/ctpbee/ctpbee/tree/dev  你clone这个分支下的本地pip安装再测试下

**Comment by somewheve** [comment]
主要是账户数量多不应该用py吧 我这个写的不怎么好 应该使用wondertrader可能会更好   只是对于单账户的dev自己写策略实现就比较舒服

**Comment by somewheve** [comment]
单账户 基本开箱即用了 啥都不用折腾

**Comment by yilin-hust** [comment]
嗯，wondertrader我看了一下，对我来说限制也很大，因为我的策略几万行代码，仓位管理资金管理还有一套逻辑，他们框架这方面的扩展性不好

**Comment by somewheve** [comment]
我推荐开多进程跑呗？ 多账户单线程比较呆

**Comment by somewheve** [comment]
如果你有啥需要我可以配合开发 我好像币的策略改的差不多了

**Comment by somewheve** [comment]
问题修复了吗 ？

**Comment by yilin-hust** [comment]
这个策略我写了两年了，现在只需要对接CTP实现程序化，后续是资金账户管理，这些都比较简单了，要实现哪些功能也是走一步看一步，代码虽然写了几万行，其实都是脚本，一个Class和Method都没有；）你这个项目抽象度很高，我看的好累：）

**Comment by yilin-hust** [comment]
已经OK了，十分感谢

**Comment by somewheve** [comment]
ok 继续慢慢改 需要啥功能发issue给我

**Comment by yilin-hust** [comment]
好的，再次感谢

**Comment by somewheve** [comment]
> 这个策略我写了两年了，现在只需要对接CTP实现程序化，后续是资金账户管理，这些都比较简单了，要实现哪些功能也是走一步看一步，代码虽然写了几万行，其实都是脚本，一个Class和Method都没有；）你这个项目抽象度很高，我看的好累：）

这个已经很简单啦  底层和上层是剥离的 中间通过signal交流的   不然得绕死你   先慢慢改单账户的   那这个问题我关闭了哈  我合并到主分支

**Comment by yilin-hust** [comment]
好的，很多时候看了这里忘 了那里，年级大了，干不动了：）

**Comment by somewheve** [comment]
hhhh没事 慢慢来 程序化后就啥都简单了   我已经发布到pypi 可以通过pip 安装了

**Comment by yilin-hust** [comment]
嗯，现在我还没数据库，之前多进程跑的，现在改成单线程了，能简单就不搞复杂了，后续有了资金管理再上考虑分布式

**Comment by somewheve** [comment]
先赚钱再说  脱离手工

**Comment by yilin-hust** [comment]
是的，主要还是多账户问题，你可帮了我大忙

**Comment by somewheve** [comment]
搞定就行 我写了bug 害

**Comment by somewheve** [comment]
hhhh大学毕业的时候写的 后面一直零零散散的维护  写不了多少功能

**Comment by yilin-hust** [comment]
厉害，我搞了10多年Java，自认水平还可以，但刚毕业时的水平真心有限
