### ISSUE TITLE
策略的断线重连

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#31]
如何在策略的时候断线的时候恢复同步 ? 
如果大佬有啥意见 ，可以提 ，我可以根据你的意见做出修改

**Comment by xiaopge** [comment]
没意见，我不懂，我觉得，连线后首先数据恢复补足断网数据，重拾和记录信号，记录缺损和未完成交易策略信号，记录断网记录

**Comment by somewheve** [comment]
我在猜想是否按照天神说的 回放行情，让策略重新过一遍行情

**Comment by xiaopge** [comment]
我觉得可以，可以现场给弄个简单策略，跑一边，给我们直播，点赞+1



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "somewheve"<notifications@github.com&gt;; 
发送时间: 2019年10月25日(星期五) 下午5:44
收件人: "ctpbee/ctpbee"<ctpbee@noreply.github.com&gt;; 
抄送: "神奇的来石"<15058835@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ctpbee/ctpbee] 策略的断线重连 (#31)




我在猜想是否按照天神说的 回放行情，让策略重新过一遍行情

**Comment by somewheve** [comment]
hhhh好的 我找时间 准备下素材
