### ISSUE TITLE
针对于连续主力合约的回测的一些猜想 

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#32]
好像可以维护一个主力合约和到期时间的链表，等到到期时间 进行切换主力合约  、
尽量做到贴合实际?  是否可以考虑移仓功能 ？ 
 如果你有什么意见 ，请在下方留言

**Comment by Wilson-G** [comment]
是的，可以定一个规则，比如2天平均的成交量都更大就切换，且大月不能切换回小月，然后维护一个change time table，再写个func计算给定日期对应合约的主力合约是什么

移仓功能可能更多是警告吧，如果用户交易的是非主力合约，就弹出一个提醒，然后一定要交易的用户可以勾选把这个合约加入白名单这样

**Comment by somewheve** [comment]
可否描述的更加详细点   按照点 和详细的场景描述

**Comment by Wilson-G** [comment]
主力合约的判断逻辑就是：比较所有在交易的月份合约交易量，谁大（or连续n天的平均交易量大）谁就是主力合约

然后维护一个主力合约切换时间点的dict：比如{'i2005':'2020-01-25','i2009':'2020-4-18'} 

这样如果你想问某个日期，这时候铁矿的主力合约是谁，就很简单了，查找一下落在哪个合约的区间里就好了。比如 2020-03-05，那自然是i2005了对吧

**Comment by somewheve** [comment]
ok

**Comment by Wilson-G** [comment]
some神怎么在群里看不见你了～发临时消息也发不出？

**Comment by somewheve** [comment]
我不在QA群里面了  你加我ctpbee的群吧   756319143

**Comment by somewheve** [comment]
此主力合约问题已经被解决 但是暂时不能开源  先关闭
