### ISSUE TITLE
docker相关问题

### ISSUE THREAD

**Issue by sea-yu** [ctpbee/ctpbee#33]
1.  docker 启动后不能自己后台运行,必须自己添加&命令才行
2.  镜像文件占了1.22G......
3.  启动后访问报了404
虚拟机,centos,
centos 版本:CentOS Linux release 8.0.1905 (Core)
docker版本:Docker version 19.03.3, build a872fc2f86  

![image](https://user-images.githubusercontent.com/37438538/67734550-53a7d300-fa3c-11e9-9e97-6bf246805425.png)

![image](https://user-images.githubusercontent.com/37438538/67734569-5dc9d180-fa3c-11e9-8bdf-eca053f1029d.png)

![image](https://user-images.githubusercontent.com/37438538/67734707-b4371000-fa3c-11e9-9b7c-feca7529ddf1.png)

![image](https://user-images.githubusercontent.com/37438538/67736059-1bef5a00-fa41-11e9-8749-4f65596e6ed9.png)

防火墙是关的,selinux是关的,本机也是404

**Comment by sea-yu** [comment]
我尝试了一下,url后面加/login,出现了登录界面,但文档中并没有给出账号密码~~~~

**Comment by somewheve** [comment]
这个docker不行的0.0  ，滞后了我后面和yutiansut再沟通下 ，还有不推荐使用docker来体验ctpbee。。

**Comment by somewheve** [comment]
登陆账号是需要去simnow申请模拟账号或者和期货公司申请实盘的 。。。

**Comment by sea-yu** [comment]
没事，我就进来看看逛逛，python不太会，就用docker试了一下，然后发现不能用，就提了个issue~~.  
centos8 对docker支持不太好~~滞后了。

**Comment by somewheve** [comment]
这个是要被弃掉的  后面要重做docker的

**Comment by somewheve** [comment]
还有学弟 换Arch吧 哈哈哈哈哈
