### ISSUE TITLE
Bugs `Indicator`的`add_bar`在opens为True时报错

### ISSUE THREAD

**Issue by shiniantianlang** [ctpbee/ctpbee#65]
**Describe the bug / 问题描述**
实盘时，在`on_bar`函数中`self.bar_3 = Indicator()`，在`self.bar_3.add_bar(bar)`时，`indicator`的`interface.py`文件中`Indicator`的`add_bar`方法的`opens`设为`True`时，报错：
```
发生异常: AttributeError
'list' object has no attribute 'endswith'
```

**Environment/ 你的运行环境**
 - OS: [e.g. Linux]
 - Python Version: [e.g.Python37]
 - ctpbee Version: [e.g. 1.0]

**Comment by somewheve** [comment]
这个只能传入单个bar而不是一个列表，注意如果你要载入历史数据你需要通过其他API        for example
self.api.open_cache(data)
