### ISSUE TITLE
CEP.[future]

### ISSUE THREAD

**Issue by somewheve** [ctpbee/ctpbee#67]
**需求/request**

想了一下量化的最终形态，先想一下作为一名普通用户我们需要啥东西，仔细一思考，其实问题很简单，我们需要的是服务。并不是编程，并不是接口，而是集成的服务，我想要一个服务

- 可以让我无缝监管我策略发生的情况 
- 可以让我让我简单的轻松添加策略或者原子任务
- 可以让我使用系统的最大性能
- 可以让我在App端简单轻松查看 
- 可以让我简单轻松获取到消息
- 可以让我拥有强大的数据支持
- 可以让我手动下单
- 可以让我一键无缝安装，直接获取服务

当前的ctpbee可能更多来说是一个开发工具而不是一个服务，我很遗憾，所以我感觉走偏了。

**最终表现效果 / result**
参上

**Comment by somewheve** [comment]
至于分布式，子节点主要提供算力节点，大概率可以使用dask将算力分配到子节点

**Comment by BaoBaoJiu** [comment]
Github上多数成熟的开源量化项目,都只开源后端,而不开源前端.  
ctpee目前提供的是给后端底层开发人员的工具,链接的是数据端.
也许构思一个新的ctpee ui框架也不错

**Comment by qiaoshan** [comment]
那策略研究放在qa上做？ctpbee是负责跑实盘？

**Comment by somewheve** [comment]
> Github上多数成熟的开源量化项目,都只开源后端,而不开源前端.
> ctpee目前提供的是给后端底层开发人员的工具,链接的是数据端.
> 也许构思一个新的ctpee ui框架也不错

这个好像也是一个出路，但是怎么讲，和我理想中要实现的不一样。

**Comment by somewheve** [comment]
> 那策略研究放在qa上做？ctpbee是负责跑实盘？

ctpbee现在就已经具备实盘功能了。 不准备在做细化了，再做下去就是和vnpy以及tqsdk在做同样的事情， 大半部分的框架都在做这个事情，这其实很蠢，用户其实不想干这个开发的事情，我个人觉得作为量化的核心用户，肯定就只有一件事，上策略，然后验证实盘， 而不是花时间在折腾接口上面， 至于为啥要做类似QA的事情，是想让用户多一种选择。当然我也会做出差异性的功能

**Comment by somewheve** [comment]
我已经开了新项目了， 后面熬夜肝吧 还要写QA文档 地址在[LevelM](https://github.com/ctpbee/LevelM)
ctpbee将作为他的子项目存活开发
