### ISSUE TITLE
安装qactpbeebroker时报错

### ISSUE THREAD

**Issue by kite8** [ctpbee/ctpbee#69]
**Describe the bug / 问题描述**
>在我安装QACTPBeeBroker，
- 弹出了`ERROR: Package 'dataclasses' requires a different Python: 3.7.6 not in '>=3.6, <3.7'`报错， 
- 我看了下ericvsmith/dataclasses的兼容性说明，dataclasses因为在3.7里是内置模块，所以这个项目只支持3.6的版本
- 我在3.7里的环境里，可以正常执行`from dataclasses import dataclass, asdict`语句，但不清楚是否影响ctpbee正常运作.
- 233, 改了好多次，其实是qactpbeebroker没做更新了，其中ctpbee限制在了0.31.2的版本，但貌似0.31.2的版本没有对python的环境做判断，所以要求安装dataclasses, 

- 最后吐槽一下自己，貌似反馈错地方了，应该去qactpbeebroker反馈

**Environment/ 你的运行环境**
 - OS: win 10
 - Python Version: Python 3.7
 - ctpbee Version: None

**Comment by somewheve** [comment]
以前版本缘故， 更新至最新版本就好了
