### ISSUE TITLE
CEP.[Number]能否考虑增加多接口支持

### ISSUE THREAD

**Issue by DeathDesigner** [ctpbee/ctpbee#72]
**多行情和交易接口**

> Interface里面固定单个核心近能设置一个借口类型，这对于需要同时是有多路数据和多交易接口的策略不太友好。

**Comment by somewheve** [comment]
我会编写一个行情推送规范   你需要实现基于次来推送就好了   晚点给你哈

**Comment by somewheve** [comment]
demo我明天写一个出来 ~~~~  sorry 有点拖迟了

**Comment by somewheve** [comment]
即将完成 但是还有点小问题
