### ISSUE TITLE
ctpbee的center脚本里，查询持仓的方法只有self.app.center.get_positon()，只能查询单个合约的持仓，没有能一次性查询账户全部持仓合约的.position()，只能另外用self.app.recorder.position_manager.get_all_positions()查询

### ISSUE THREAD

**Issue by QuantWanderer** [ctpbee/ctpbee#73]
**Describe the bug / 问题描述**
> 请在此处描述问题

**To Reproduce / 复现步骤 **

**Expected behavior / 期望结果**

**Screenshots / 截图**

If applicable, add screenshots to help explain your problem./如果可能请将截图放于此处

**Environment/ 你的运行环境**
 - OS: [e.g. Linux]
 - Python Version: [e.g.Python36]
 - ctpbee Version: [e.g. 0.50]

**Comment by somewheve** [comment]
已经修复了  但是还没有上传新版本
